---
# ------------------------------------------------------------------------------
# Install NTP for cluster
# ------------------------------------------------------------------------------

- block:
  - name:               "Install NTP for cluster"
    yum:
      name:             ntp
      state:            installed

  - name:               "Fix for bug 19427746 in OEL 7+"
    copy:
      src:              ntpd
      dest:             /etc/sysconfig/ntpd
      owner:            root
      group:            root
      mode:             "u=rw,g=r,o=r"
    notify:
      - restart ntpd
    when:
      - ansible_distribution_file_variety      == "OracleLinux"
      - ansible_distribution_major_version|int >= 7 


  - name:               "Ensure NTPD is running and enabled"
    service:
      name:             ntpd
      state:            started
      enabled:          yes
  tags:                 ntp
  become:               yes
  become_user:          root

...
